import test, {beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {db} from '../db';
import {products,categories,orders,orderItems,reviews,productImages,storeSettings,users} from '../db/schema';
import {eq,sql} from 'drizzle-orm';
import {createOrder} from '../lib/checkout';
import {updateOrder,deleteOrder} from '../lib/order-management';
import {saveProduct,removeProduct,saveCategory,removeCategory} from '../lib/catalogue';
import {publicSettings,courierCredentials} from '../lib/settings';
import {validPhone,deliveryFee} from '../lib/validation';

assert.match(process.env.TURSO_DATABASE_URL || '',/^file:.*\/\.audit\/commerce-test\.db$/,'Tests must use the isolated test database.');
beforeEach(async()=>{
 for(const table of [orderItems,orders,reviews,productImages,products,categories,storeSettings,users]) await db.delete(table);
 await db.insert(products).values([{id:'p1',name:'Test ESP32',slug:'test-esp32',price:450,stock:5,createdAt:new Date(),updatedAt:new Date()},{id:'p2',name:'Test Capacitor',slug:'test-capacitor',price:20,stock:2,createdAt:new Date(),updatedAt:new Date()}]);
});
function checkout(extra:Record<string,unknown>={}){return {customerName:'Audit Customer',customerPhone:'+8801712345678',address:'Synthetic test address',shippingCity:'Dhaka',paymentMethod:'cod',items:[{id:'p1',quantity:2,price:1}],total:2,deliveryCharge:-500,...extra};}
async function stock(id='p1'){return (await db.query.products.findFirst({where:eq(products.id,id)}))!.stock;}
test('server controls prices and shipping',async()=>{const order=await createOrder(checkout());assert.equal(order.total,960);assert.equal(await stock(),3);const row=await db.query.orders.findFirst();assert.equal(row?.customerPhone,'01712345678');assert.equal(row?.status,'PENDING');assert.equal(row?.courierTrackingId,null);});
test('all delivery zones are consistent',()=>{assert.equal(deliveryFee('Dhaka'),60);assert.equal(deliveryFee('Dhaka Suburbs (Gazipur/Savar/Narayanganj)'),100);assert.equal(deliveryFee('Outside Dhaka'),120);});
test('admin can set zero delivery fee',async()=>{const order=await createOrder(checkout({deliveryCharge:0}),{id:'admin-platform',role:'admin'});assert.equal(order.total,900);});
test('customer cannot override delivery',async()=>{const order=await createOrder(checkout({deliveryCharge:0,shippingCity:'Outside Dhaka'}));assert.equal(order.total,1020);});
test('normalizes Bengali and international phone numbers',()=>{assert.equal(validPhone('০১৭১২৩৪৫৬৭৮'),'01712345678');assert.equal(validPhone('+880 1712-345678'),'01712345678');assert.throws(()=>validPhone('123'));});
for(const quantity of [-2,0,1.5,'NaN',10001]) test('rejects invalid quantity '+quantity,async()=>{await assert.rejects(createOrder(checkout({items:[{id:'p1',quantity}]})));assert.equal(await stock(),5);assert.equal((await db.select().from(orders)).length,0);});
test('oversold order rolls back all reservations',async()=>{await assert.rejects(createOrder(checkout({items:[{id:'p1',quantity:2},{id:'p2',quantity:3}]})),/Only 2/);assert.equal(await stock(),5);assert.equal(await stock('p2'),2);});
test('aggregates duplicate product lines before reservation',async()=>{await assert.rejects(createOrder(checkout({items:[{id:'p1',quantity:3},{id:'p1',quantity:3}]})),/Only 5/);assert.equal(await stock(),5);});
test('checkout retries are idempotent',async()=>{const data=checkout({requestId:crypto.randomUUID()});const a=await createOrder(data);const b=await createOrder(data);assert.equal(a.orderId,b.orderId);assert.equal(await stock(),3);assert.equal((await db.select().from(orders)).length,1);});
test('reusing a request for another order is rejected',async()=>{const data=checkout({requestId:crypto.randomUUID()});await createOrder(data);await assert.rejects(createOrder({...data,address:'Different address'}),/already been submitted/);});
test('concurrent customers cannot buy the same final unit',async()=>{await db.update(products).set({stock:1}).where(eq(products.id,'p1'));const payload=checkout({items:[{id:'p1',quantity:1}]});const outcomes=await Promise.allSettled([createOrder(payload),createOrder(payload)]);assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);assert.equal(await stock(),0);assert.equal((await db.select().from(orders)).length,1);});
test('cancellation returns stock exactly once',async()=>{const o=await createOrder(checkout());await updateOrder(o.orderId,{status:'CANCELLED'});await updateOrder(o.orderId,{status:'CANCELLED'});assert.equal(await stock(),5);await assert.rejects(updateOrder(o.orderId,{status:'PENDING'}),/cannot be reopened/);});
test('dispatched cancellation does not restock goods still in transit',async()=>{const o=await createOrder(checkout());await updateOrder(o.orderId,{trackingCode:'test-courier-code'});await updateOrder(o.orderId,{status:'CANCELLED'});assert.equal(await stock(),3);});
test('manually shipped cancellation does not restock goods in transit',async()=>{const o=await createOrder(checkout());await updateOrder(o.orderId,{status:'SHIPPED'});await updateOrder(o.orderId,{status:'CANCELLED'});assert.equal(await stock(),3);});
test('pending courier dispatch cannot race cancellation or a tracking override',async()=>{const o=await createOrder(checkout());await db.update(orders).set({courierTrackingId:'DISPATCH_PENDING:'+o.orderId}).where(eq(orders.id,o.orderId));await assert.rejects(updateOrder(o.orderId,{status:'CANCELLED'}),/Resolve the pending/);await assert.rejects(updateOrder(o.orderId,{trackingCode:''}),/still in progress/);assert.equal(await stock(),3);});
test('only cancelled undispatched orders can be deleted',async()=>{const o=await createOrder(checkout());await assert.rejects(deleteOrder(o.orderId),/Cancel the order first/);await updateOrder(o.orderId,{status:'CANCELLED'});await deleteOrder(o.orderId);assert.equal((await db.select().from(orders)).length,0);assert.equal((await db.select().from(orderItems)).length,0);assert.equal(await stock(),5);});
test('invalid statuses do not change records',async()=>{const o=await createOrder(checkout());await assert.rejects(updateOrder(o.orderId,{status:'whatever'}));await assert.rejects(updateOrder(o.orderId,{paymentStatus:'PAID?'}));});
test('unconfigured payment methods are unavailable',async()=>{await assert.rejects(createOrder(checkout({paymentMethod:'nagad',transactionId:'TEST1234'})),/unavailable/);await assert.rejects(createOrder(checkout({paymentMethod:'wire'})),/Invalid payment/);});
test('prepaid orders require transaction ID and verification before shipping',async()=>{await db.insert(storeSettings).values({key:'bkash_number',value:'01712345678',updatedAt:new Date()});await assert.rejects(createOrder(checkout({paymentMethod:'bkash'})));const o=await createOrder(checkout({paymentMethod:'bkash',transactionId:'TEST12345'}));await assert.rejects(updateOrder(o.orderId,{status:'SHIPPED'}),/Verify payment/);await updateOrder(o.orderId,{paymentStatus:'VERIFIED',status:'SHIPPED'});});
test('private courier settings never enter public settings',async()=>{await db.insert(storeSettings).values([{key:'steadfast_secret_key',value:'test-only-secret',updatedAt:new Date()},{key:'phone',value:'01712345678',updatedAt:new Date()}]);const visible=await publicSettings();assert.equal(visible.steadfast_secret_key,undefined);assert.equal(visible.phone,'01712345678');assert.equal((await courierCredentials()).secretKey,'test-only-secret');});
test('product creation and edit preserve slug and validate specifications',async()=>{const id=await saveProduct({name:'Board',price:100,stock:3,specs:'{"Voltage":"3.3V"}',category:'Controllers'});const before=await db.query.products.findFirst({where:eq(products.id,id)});await saveProduct({name:'Board revised',price:90},id);assert.equal((await db.query.products.findFirst({where:eq(products.id,id)}))?.slug,before?.slug);await assert.rejects(saveProduct({price:-1},id));await assert.rejects(saveProduct({stock:1.4},id));await assert.rejects(saveProduct({specs:'broken JSON'},id));});
test('product with order history cannot be deleted or lose images',async()=>{await db.insert(productImages).values({id:'img',productId:'p1',url:'https://example.org/a.png',sortOrder:0});await createOrder(checkout());await assert.rejects(removeProduct('p1'),/order history/);assert.equal((await db.select().from(productImages)).length,1);});
test('category rename retains links and delete unassigns products',async()=>{const id=await saveCategory({name:'Controllers'});const slug=(await db.query.categories.findFirst({where:eq(categories.id,id)}))?.slug;await saveProduct({categoryId:id},'p1');await saveCategory({name:'Microcontrollers'},id);assert.equal((await db.query.categories.findFirst({where:eq(categories.id,id)}))?.slug,slug);await removeCategory(id);assert.equal((await db.query.products.findFirst({where:eq(products.id,'p1')}))?.categoryId,null);});
test('product and images are atomic on invalid image input',async()=>{await assert.rejects(saveProduct({name:'Bad upload',price:50,images:['javascript:alert(1)']}));assert.equal((await db.select().from(products)).length,2);});
test('editing a name cannot overwrite stock reserved by concurrent checkout',async()=>{await Promise.all([createOrder(checkout()),saveProduct({name:'Updated test board'},'p1')]);assert.equal(await stock(),3);});
